#!/bin/bash

$TARGET-as boot.s -o boot.o
$TARGET-gcc -c kernel.c -o kernel.o -std=gnu99 -ffreestanding -O2 -Wall -Wextra
$TARGET-gcc -T linker.ld -o myos.bin -ffreestanding -O2 -nostdlib boot.o kernel.o -lgcc
#mkdir -p isodir/boot/grub
#cp build/grub.cfg isodir/boot/grub/grub.cfg
#cp myos.bin isodir/boot/myos.bin
#qemu-system-i386 -cdrom myos.iso
qemu-system-i386 -kernel myos.bin
